services:
  mysql:
    image: mysql:8.0
    container_name: cyphlab-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cyphlab
    ports:
      - "3306:3306"
    volumes:
      - cyphlab-mysql-data:/var/lib/mysql

volumes:
  cyphlab-mysql-data:
